modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
[[mods]] 
modId="${mod_id}" 
version="${mod_version}"
displayName="${mod_name}" 
logoFile="icon.png" 
authors="${mod_authors}"
description='''${mod_description}'''
[[dependencies.${mod_id}]]
    modId="forge" 
    mandatory=true 
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="azurelib"
    mandatory=true
    versionRange="[1.0.15,)"
    ordering="BEFORE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="curios"
    mandatory=true 
    versionRange="[5.2.0-beta.1+1.20,)" 
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="smartbrainlib"
    mandatory=true 
    versionRange="[1.11,)" 
    ordering="NONE"
    side="BOTH"    