modLoader="javafml"
loaderVersion="[42,)"
license="CC-BY-NC-4.0"
[[mods]]
modId="doom"
version="${file.jarVersion}"
displayName="Doom Mod"
logoFile="icon.png"
authors="AzureDoomC" 
description='''
Adds Doom into Minecraft
'''
[[dependencies.doom]]
    modId="geckolib3"
    mandatory=true
    versionRange="[3.1.34,)"
    ordering="BEFORE"
    side="BOTH"
[[dependencies.doom]]
    modId="forge"
    mandatory=true 
    versionRange="[42.0.0,)" 
    ordering="NONE"
    side="BOTH"
[[dependencies.doom]]
    modId="curios"
    mandatory=true 
    versionRange="[1.19.2-5.1.1.0,)" 
    ordering="NONE"
    side="BOTH"