modLoader="javafml"
loaderVersion="[44,)"
license="CC-BY-NC-4.0"
[[mods]]
modId="doom"
version="${file.jarVersion}"
displayName="Doom Mod"
logoFile="icon.png"
authors="AzureDoomC" 
description='''
Adds Doom into Minecraft
'''
[[dependencies.doom]]
    modId="azurelib"
    mandatory=true
    versionRange="[1.0.0,)"
    ordering="BEFORE"
    side="BOTH"
[[dependencies.doom]]
    modId="forge"
    mandatory=true 
    versionRange="[44.0.37,)" 
    ordering="NONE"
    side="BOTH"
[[dependencies.doom]]
    modId="curios"
    mandatory=true 
    versionRange="[1.19.3-5.1.1.2,)" 
    ordering="NONE"
    side="BOTH"