modLoader="javafml"
loaderVersion="[37,)"
license="CC-BY-NC-4.0"
[[mods]]
modId="doom"
version="${file.jarVersion}"
displayName="Doom Mod"
logoFile="doomlogo.png"
authors="AzureDoomC" 
description='''
Adds Doom into Minecraft
'''
[[dependencies.geckolib]]
    modId="geckolib3"
    mandatory=true
    versionRange="[3.0.10,)"
    ordering="BEFORE"
    side="BOTH"
[[dependencies.forge]]
    modId="forge"
    mandatory=true 
    versionRange="[37.0.59,)" 
    ordering="NONE"
    side="BOTH"