modLoader="javafml"
loaderVersion="[45,)"
license="CC-BY-NC-4.0"
[[mods]]
modId="doom"
version="${file.jarVersion}"
displayName="Doom Mod"
logoFile="icon.png"
authors="AzureDoomC" 
description='''
Adds Doom into Minecraft
'''
[[dependencies.doom]]
    modId="azurelib"
    mandatory=true
    versionRange="[1.0.11,)"
    ordering="BEFORE"
    side="BOTH"
[[dependencies.doom]]
    modId="forge"
    mandatory=true 
    versionRange="[45.0.43,)" 
    ordering="NONE"
    side="BOTH"
[[dependencies.doom]]
    modId="curios"
    mandatory=true 
    versionRange="[1.19.4-5.1.4.3,)" 
    ordering="NONE"
    side="BOTH"
[[dependencies.doom]]
    modId="smartbrainlib"
    mandatory=true 
    versionRange="[1.9,)" 
    ordering="NONE"
    side="BOTH"