modLoader="javafml"
loaderVersion="[41,)"
license="CC-BY-NC-4.0"
[[mods]]
modId="doom"
version="${file.jarVersion}"
displayName="Doom Mod"
logoFile="icon.png"
authors="AzureDoomC" 
description='''
Adds Doom into Minecraft
'''
[[dependencies.geckolib]]
    modId="geckolib3"
    mandatory=true
    versionRange="[3.1.0,)"
    ordering="BEFORE"
    side="BOTH"
[[dependencies.forge]]
    modId="forge"
    mandatory=true 
    versionRange="[41.0.0,)" 
    ordering="NONE"
    side="BOTH"