modLoader="javafml"
loaderVersion="[46,)"
license="CC-BY-NC-4.0"
[[mods]]
modId="doom"
version="${file.jarVersion}"
displayName="Doom Mod"
logoFile="icon.png"
authors="AzureDoomC" 
description='''
Adds Doom into Minecraft
'''
[[dependencies.doom]]
    modId="azurelib"
    mandatory=true
    versionRange="[1.0.11,)"
    ordering="BEFORE"
    side="BOTH"
[[dependencies.doom]]
    modId="forge"
    mandatory=true 
    versionRange="[46.0.14,)" 
    ordering="NONE"
    side="BOTH"
[[dependencies.doom]]
    modId="curios"
    mandatory=true 
    versionRange="[5.2.0-beta.1+1.20,)" 
    ordering="NONE"
    side="BOTH"
[[dependencies.doom]]
    modId="smartbrainlib"
    mandatory=true 
    versionRange="[1.11,)" 
    ordering="NONE"
    side="BOTH"