package mod.azure.doom.items.armor;

public enum ArmorTypeEnum {
    ASTRO, BRONZE, CLASSIC_GREEN, CLASSIC_RED, CLASSIC_INDIGO, CRIMSON, CULTIST, DARK_LORD, DEMONIC, DOOMICORN, EMBER, GOLD, HOTROD, MAYKR, MIDNIGHT, MULLET1, MULLET2, MULLET3, NIGHTMARE, PAINTER, PHOBOS, PRAETOR, PURPLE_PONY, SANTA, SENTINEL, TWENTYFIVE, ZOMBIE, DOOM, CLASSIC_BRONZE, DEMONCIDE
}
