package mod.azure.doom.util;

import mod.azure.doom.DoomMod;
import mod.azure.doom.entity.DemonEntity;
import mod.azure.doom.entity.tierambient.CueBallEntity;
import mod.azure.doom.entity.tierambient.GoreNestEntity;
import mod.azure.doom.entity.tierambient.TentacleEntity;
import mod.azure.doom.entity.tierambient.TurretEntity;
import mod.azure.doom.entity.tierboss.ArchMakyrEntity;
import mod.azure.doom.entity.tierboss.GladiatorEntity;
import mod.azure.doom.entity.tierboss.IconofsinEntity;
import mod.azure.doom.entity.tierboss.MotherDemonEntity;
import mod.azure.doom.entity.tierboss.SpiderMastermind2016Entity;
import mod.azure.doom.entity.tierboss.SpiderMastermindEntity;
import mod.azure.doom.entity.tierfodder.ChaingunnerEntity;
import mod.azure.doom.entity.tierfodder.GargoyleEntity;
import mod.azure.doom.entity.tierfodder.ImpEntity;
import mod.azure.doom.entity.tierfodder.ImpStoneEntity;
import mod.azure.doom.entity.tierfodder.LostSoulEntity;
import mod.azure.doom.entity.tierfodder.MaykrDroneEntity;
import mod.azure.doom.entity.tierfodder.MechaZombieEntity;
import mod.azure.doom.entity.tierfodder.PossessedScientistEntity;
import mod.azure.doom.entity.tierfodder.PossessedSoldierEntity;
import mod.azure.doom.entity.tierfodder.ShotgunguyEntity;
import mod.azure.doom.entity.tierfodder.UnwillingEntity;
import mod.azure.doom.entity.tierfodder.ZombiemanEntity;
import mod.azure.doom.entity.tierheavy.ArachnotronEntity;
import mod.azure.doom.entity.tierheavy.BloodMaykrEntity;
import mod.azure.doom.entity.tierheavy.CacodemonEntity;
import mod.azure.doom.entity.tierheavy.Hellknight2016Entity;
import mod.azure.doom.entity.tierheavy.HellknightEntity;
import mod.azure.doom.entity.tierheavy.MancubusEntity;
import mod.azure.doom.entity.tierheavy.PainEntity;
import mod.azure.doom.entity.tierheavy.PinkyEntity;
import mod.azure.doom.entity.tierheavy.ProwlerEntity;
import mod.azure.doom.entity.tierheavy.Revenant2016Entity;
import mod.azure.doom.entity.tierheavy.RevenantEntity;
import mod.azure.doom.entity.tierheavy.SpectreEntity;
import mod.azure.doom.entity.tierheavy.WhiplashEntity;
import mod.azure.doom.entity.tiersuperheavy.ArchvileEntity;
import mod.azure.doom.entity.tiersuperheavy.ArmoredBaronEntity;
import mod.azure.doom.entity.tiersuperheavy.BaronEntity;
import mod.azure.doom.entity.tiersuperheavy.CyberdemonEntity;
import mod.azure.doom.entity.tiersuperheavy.DoomHunterEntity;
import mod.azure.doom.entity.tiersuperheavy.FireBaronEntity;
import mod.azure.doom.entity.tiersuperheavy.MarauderEntity;
import mod.azure.doom.entity.tiersuperheavy.SummonerEntity;
import mod.azure.doom.util.registry.DoomEntities;
import net.minecraft.world.entity.SpawnPlacements;
import net.minecraft.world.level.levelgen.Heightmap;
import net.minecraftforge.event.entity.EntityAttributeCreationEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod.EventBusSubscriber;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegisterEvent;

@EventBusSubscriber(modid = DoomMod.MODID, bus = EventBusSubscriber.Bus.MOD)
public class ModEventSubscriber {

	@SubscribeEvent
	public static void onRegisterEvent(RegisterEvent event) {
		event.register(ForgeRegistries.Keys.ENTITY_TYPES, helper -> {
			SpawnPlacements.register(DoomEntities.GLADIATOR.get(), SpawnPlacements.Type.ON_GROUND,
					Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::canSpawnInDark);
			SpawnPlacements.register(DoomEntities.ARCHVILE.get(), SpawnPlacements.Type.ON_GROUND,
					Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::canSpawnInDark);
			SpawnPlacements.register(DoomEntities.LOST_SOUL.get(), SpawnPlacements.Type.ON_GROUND,
					Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::canSpawnInDark);
			SpawnPlacements.register(DoomEntities.LOST_SOUL_ETERNAL.get(), SpawnPlacements.Type.ON_GROUND,
					Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::canSpawnInDark);
			SpawnPlacements.register(DoomEntities.ZOMBIEMAN.get(), SpawnPlacements.Type.ON_GROUND,
					Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::canSpawnInDark);
			SpawnPlacements.register(DoomEntities.SPIDERMASTERMIND.get(), SpawnPlacements.Type.ON_GROUND,
					Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::canSpawnInDark);
			SpawnPlacements.register(DoomEntities.ARACHNOTRON.get(), SpawnPlacements.Type.ON_GROUND,
					Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::canSpawnInDark);
			SpawnPlacements.register(DoomEntities.MANCUBUS.get(), SpawnPlacements.Type.ON_GROUND,
					Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::canSpawnInDark);
			SpawnPlacements.register(DoomEntities.BARON.get(), SpawnPlacements.Type.ON_GROUND,
					Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::canSpawnInDark);
			SpawnPlacements.register(DoomEntities.REVENANT.get(), SpawnPlacements.Type.ON_GROUND,
					Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::canSpawnInDark);
			SpawnPlacements.register(DoomEntities.IMP.get(), SpawnPlacements.Type.ON_GROUND,
					Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::canSpawnInDark);
			SpawnPlacements.register(DoomEntities.PINKY.get(), SpawnPlacements.Type.ON_GROUND,
					Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::canSpawnInDark);
			SpawnPlacements.register(DoomEntities.SPECTRE.get(), SpawnPlacements.Type.ON_GROUND,
					Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::canSpawnInDark);
			SpawnPlacements.register(DoomEntities.CACODEMON.get(), SpawnPlacements.Type.ON_GROUND,
					Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::canSpawnInDark);
			SpawnPlacements.register(DoomEntities.CHAINGUNNER.get(), SpawnPlacements.Type.ON_GROUND,
					Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::canSpawnInDark);
			SpawnPlacements.register(DoomEntities.MARAUDER.get(), SpawnPlacements.Type.ON_GROUND,
					Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::canSpawnInDark);
			SpawnPlacements.register(DoomEntities.SHOTGUNGUY.get(), SpawnPlacements.Type.ON_GROUND,
					Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::canSpawnInDark);
			SpawnPlacements.register(DoomEntities.PAIN.get(), SpawnPlacements.Type.IN_LAVA,
					Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::canSpawnInDark);
			SpawnPlacements.register(DoomEntities.HELLKNIGHT.get(), SpawnPlacements.Type.ON_GROUND,
					Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::canSpawnInDark);
			SpawnPlacements.register(DoomEntities.HELLKNIGHT2016.get(), SpawnPlacements.Type.ON_GROUND,
					Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::canSpawnInDark);
			SpawnPlacements.register(DoomEntities.CYBERDEMON.get(), SpawnPlacements.Type.ON_GROUND,
					Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::canSpawnInDark);
			SpawnPlacements.register(DoomEntities.UNWILLING.get(), SpawnPlacements.Type.ON_GROUND,
					Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::canSpawnInDark);
			SpawnPlacements.register(DoomEntities.POSSESSEDSCIENTIST.get(), SpawnPlacements.Type.ON_GROUND,
					Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::canSpawnInDark);
			SpawnPlacements.register(DoomEntities.POSSESSEDSOLDIER.get(), SpawnPlacements.Type.ON_GROUND,
					Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::canSpawnInDark);
			SpawnPlacements.register(DoomEntities.ICONOFSIN.get(), SpawnPlacements.Type.ON_GROUND,
					Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::canSpawnInDark);
			SpawnPlacements.register(DoomEntities.GORE_NEST.get(), SpawnPlacements.Type.ON_GROUND,
					Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::canSpawnInDark);
			SpawnPlacements.register(DoomEntities.MECHAZOMBIE.get(), SpawnPlacements.Type.ON_GROUND,
					Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::canSpawnInDark);
			SpawnPlacements.register(DoomEntities.GARGOYLE.get(), SpawnPlacements.Type.ON_GROUND,
					Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::canSpawnInDark);
			SpawnPlacements.register(DoomEntities.CUEBALL.get(), SpawnPlacements.Type.ON_GROUND,
					Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::canSpawnInDark);
			SpawnPlacements.register(DoomEntities.PROWLER.get(), SpawnPlacements.Type.ON_GROUND,
					Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::canSpawnInDark);
			SpawnPlacements.register(DoomEntities.DREADKNIGHT.get(), SpawnPlacements.Type.ON_GROUND,
					Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::canSpawnInDark);
			SpawnPlacements.register(DoomEntities.IMP_STONE.get(), SpawnPlacements.Type.ON_GROUND,
					Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::canSpawnInDark);
			SpawnPlacements.register(DoomEntities.POSSESSEDWORKER.get(), SpawnPlacements.Type.ON_GROUND,
					Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::canSpawnInDark);
			SpawnPlacements.register(DoomEntities.DOOMHUNTER.get(), SpawnPlacements.Type.ON_GROUND,
					Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::canSpawnInDark);
			SpawnPlacements.register(DoomEntities.WHIPLASH.get(), SpawnPlacements.Type.ON_GROUND,
					Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::canSpawnInDark);
			SpawnPlacements.register(DoomEntities.FIREBARON.get(), SpawnPlacements.Type.ON_GROUND,
					Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::canSpawnInDark);
			SpawnPlacements.register(DoomEntities.BARON2016.get(), SpawnPlacements.Type.ON_GROUND,
					Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::canSpawnInDark);
			SpawnPlacements.register(DoomEntities.ARMORBARON.get(), SpawnPlacements.Type.ON_GROUND,
					Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::canSpawnInDark);
			SpawnPlacements.register(DoomEntities.ARACHNOTRONETERNAL.get(), SpawnPlacements.Type.ON_GROUND,
					Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::canSpawnInDark);
			SpawnPlacements.register(DoomEntities.MAYKRDRONE.get(), SpawnPlacements.Type.ON_GROUND,
					Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::canSpawnInDark);
			SpawnPlacements.register(DoomEntities.SPIDERMASTERMIND2016.get(), SpawnPlacements.Type.ON_GROUND,
					Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::canSpawnInDark);
			SpawnPlacements.register(DoomEntities.BLOODMAYKR.get(), SpawnPlacements.Type.ON_GROUND,
					Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::canSpawnInDark);
			SpawnPlacements.register(DoomEntities.ARCHMAKER.get(), SpawnPlacements.Type.ON_GROUND,
					Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::canSpawnInDark);
			SpawnPlacements.register(DoomEntities.TENTACLE.get(), SpawnPlacements.Type.ON_GROUND,
					Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::canSpawnInDark);
			SpawnPlacements.register(DoomEntities.MOTHERDEMON.get(), SpawnPlacements.Type.ON_GROUND,
					Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::canSpawnInDark);
			SpawnPlacements.register(DoomEntities.TURRET.get(), SpawnPlacements.Type.ON_GROUND,
					Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::canSpawnInDark);
			SpawnPlacements.register(DoomEntities.SUMMONER.get(), SpawnPlacements.Type.ON_GROUND,
					Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::canSpawnInDark);
			SpawnPlacements.register(DoomEntities.REVENANT2016.get(), SpawnPlacements.Type.ON_GROUND,
					Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::canSpawnInDark);
		});
	}

	@SubscribeEvent
	public static void entityAttributes(EntityAttributeCreationEvent event) {
		event.put(DoomEntities.GLADIATOR.get(), GladiatorEntity.createMobAttributes().build());
		event.put(DoomEntities.CYBERDEMON.get(), CyberdemonEntity.createMobAttributes().build());
		event.put(DoomEntities.ARCHVILE.get(), ArchvileEntity.createMobAttributes().build());
		event.put(DoomEntities.BARON.get(), BaronEntity.createMobAttributes().build());
		event.put(DoomEntities.CHAINGUNNER.get(), ChaingunnerEntity.createMobAttributes().build());
		event.put(DoomEntities.HELLKNIGHT.get(), HellknightEntity.createMobAttributes().build());
		event.put(DoomEntities.HELLKNIGHT2016.get(), Hellknight2016Entity.createMobAttributes().build());
		event.put(DoomEntities.ICONOFSIN.get(), IconofsinEntity.createMobAttributes().build());
		event.put(DoomEntities.IMP.get(), ImpEntity.createMobAttributes().build());
		event.put(DoomEntities.MANCUBUS.get(), MancubusEntity.createMobAttributes().build());
		event.put(DoomEntities.MARAUDER.get(), MarauderEntity.createMobAttributes().build());
		event.put(DoomEntities.PINKY.get(), PinkyEntity.createMobAttributes().build());
		event.put(DoomEntities.SPECTRE.get(), SpectreEntity.createMobAttributes().build());
		event.put(DoomEntities.LOST_SOUL.get(), LostSoulEntity.createMobAttributes().build());
		event.put(DoomEntities.LOST_SOUL_ETERNAL.get(), LostSoulEntity.createMobAttributes().build());
		event.put(DoomEntities.POSSESSEDSCIENTIST.get(), PossessedScientistEntity.createMobAttributes().build());
		event.put(DoomEntities.POSSESSEDSOLDIER.get(), PossessedSoldierEntity.createMobAttributes().build());
		event.put(DoomEntities.REVENANT.get(), RevenantEntity.createMobAttributes().build());
		event.put(DoomEntities.SHOTGUNGUY.get(), ShotgunguyEntity.createMobAttributes().build());
		event.put(DoomEntities.ARACHNOTRON.get(), ArachnotronEntity.createMobAttributes().build());
		event.put(DoomEntities.SPIDERMASTERMIND.get(), SpiderMastermindEntity.createMobAttributes().build());
		event.put(DoomEntities.UNWILLING.get(), UnwillingEntity.createMobAttributes().build());
		event.put(DoomEntities.ZOMBIEMAN.get(), ZombiemanEntity.createMobAttributes().build());
		event.put(DoomEntities.CACODEMON.get(), CacodemonEntity.createMobAttributes().build());
		event.put(DoomEntities.PAIN.get(), PainEntity.createMobAttributes().build());
		event.put(DoomEntities.GORE_NEST.get(), GoreNestEntity.createMobAttributes().build());
		event.put(DoomEntities.MECHAZOMBIE.get(), MechaZombieEntity.createMobAttributes().build());
		event.put(DoomEntities.GARGOYLE.get(), GargoyleEntity.createMobAttributes().build());
		event.put(DoomEntities.CUEBALL.get(), CueBallEntity.createMobAttributes().build());
		event.put(DoomEntities.PROWLER.get(), ProwlerEntity.createMobAttributes().build());
		event.put(DoomEntities.DREADKNIGHT.get(), Hellknight2016Entity.createMobAttributes().build());
		event.put(DoomEntities.IMP_STONE.get(), ImpStoneEntity.createMobAttributes().build());
		event.put(DoomEntities.POSSESSEDWORKER.get(), PossessedScientistEntity.createMobAttributes().build());
		event.put(DoomEntities.DOOMHUNTER.get(), DoomHunterEntity.createMobAttributes().build());
		event.put(DoomEntities.WHIPLASH.get(), WhiplashEntity.createMobAttributes().build());
		event.put(DoomEntities.BARON2016.get(), BaronEntity.createMobAttributes().build());
		event.put(DoomEntities.ARMORBARON.get(), ArmoredBaronEntity.createMobAttributes().build());
		event.put(DoomEntities.ARACHNOTRONETERNAL.get(), ArachnotronEntity.createMobAttributes().build());
		event.put(DoomEntities.MAYKRDRONE.get(), MaykrDroneEntity.createMobAttributes().build());
		event.put(DoomEntities.SPIDERMASTERMIND2016.get(), SpiderMastermind2016Entity.createMobAttributes().build());
		event.put(DoomEntities.BLOODMAYKR.get(), BloodMaykrEntity.createMobAttributes().build());
		event.put(DoomEntities.ARCHMAKER.get(), ArchMakyrEntity.createMobAttributes().build());
		event.put(DoomEntities.FIREBARON.get(), FireBaronEntity.createMobAttributes().build());
		event.put(DoomEntities.TENTACLE.get(), TentacleEntity.createMobAttributes().build());
		event.put(DoomEntities.MOTHERDEMON.get(), MotherDemonEntity.createMobAttributes().build());
		event.put(DoomEntities.TURRET.get(), TurretEntity.createMobAttributes().build());
		event.put(DoomEntities.SUMMONER.get(), SummonerEntity.createMobAttributes().build());
		event.put(DoomEntities.REVENANT2016.get(), Revenant2016Entity.createMobAttributes().build());
	}
}