package mod.azure.doom.util;

import mod.azure.doom.DoomMod;
import mod.azure.doom.entity.DemonEntity;
import mod.azure.doom.entity.tierambient.CueBallEntity;
import mod.azure.doom.entity.tierambient.GoreNestEntity;
import mod.azure.doom.entity.tierambient.TentacleEntity;
import mod.azure.doom.entity.tierambient.TurretEntity;
import mod.azure.doom.entity.tierboss.ArchMakyrEntity;
import mod.azure.doom.entity.tierboss.GladiatorEntity;
import mod.azure.doom.entity.tierboss.IconofsinEntity;
import mod.azure.doom.entity.tierboss.MotherDemonEntity;
import mod.azure.doom.entity.tierboss.SpiderMastermind2016Entity;
import mod.azure.doom.entity.tierboss.SpiderMastermindEntity;
import mod.azure.doom.entity.tierfodder.ChaingunnerEntity;
import mod.azure.doom.entity.tierfodder.GargoyleEntity;
import mod.azure.doom.entity.tierfodder.ImpEntity;
import mod.azure.doom.entity.tierfodder.ImpStoneEntity;
import mod.azure.doom.entity.tierfodder.LostSoulEntity;
import mod.azure.doom.entity.tierfodder.MaykrDroneEntity;
import mod.azure.doom.entity.tierfodder.MechaZombieEntity;
import mod.azure.doom.entity.tierfodder.PossessedScientistEntity;
import mod.azure.doom.entity.tierfodder.PossessedSoldierEntity;
import mod.azure.doom.entity.tierfodder.ShotgunguyEntity;
import mod.azure.doom.entity.tierfodder.UnwillingEntity;
import mod.azure.doom.entity.tierfodder.ZombiemanEntity;
import mod.azure.doom.entity.tierheavy.ArachnotronEntity;
import mod.azure.doom.entity.tierheavy.BloodMaykrEntity;
import mod.azure.doom.entity.tierheavy.CacodemonEntity;
import mod.azure.doom.entity.tierheavy.Hellknight2016Entity;
import mod.azure.doom.entity.tierheavy.HellknightEntity;
import mod.azure.doom.entity.tierheavy.MancubusEntity;
import mod.azure.doom.entity.tierheavy.PainEntity;
import mod.azure.doom.entity.tierheavy.PinkyEntity;
import mod.azure.doom.entity.tierheavy.ProwlerEntity;
import mod.azure.doom.entity.tierheavy.Revenant2016Entity;
import mod.azure.doom.entity.tierheavy.RevenantEntity;
import mod.azure.doom.entity.tierheavy.SpectreEntity;
import mod.azure.doom.entity.tierheavy.WhiplashEntity;
import mod.azure.doom.entity.tiersuperheavy.ArchvileEntity;
import mod.azure.doom.entity.tiersuperheavy.ArmoredBaronEntity;
import mod.azure.doom.entity.tiersuperheavy.BaronEntity;
import mod.azure.doom.entity.tiersuperheavy.CyberdemonEntity;
import mod.azure.doom.entity.tiersuperheavy.DoomHunterEntity;
import mod.azure.doom.entity.tiersuperheavy.FireBaronEntity;
import mod.azure.doom.entity.tiersuperheavy.MarauderEntity;
import mod.azure.doom.entity.tiersuperheavy.SummonerEntity;
import mod.azure.doom.util.registry.DoomEntities;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.SpawnPlacements;
import net.minecraft.world.level.levelgen.Heightmap;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.event.entity.EntityAttributeCreationEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod.EventBusSubscriber;

@EventBusSubscriber(modid = DoomMod.MODID, bus = EventBusSubscriber.Bus.MOD)
public class ModEventSubscriber {

	@SubscribeEvent
	public static void registerEntities(final RegistryEvent.Register<EntityType<?>> event) {
		SpawnPlacements.register(DoomEntities.GLADIATOR.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::passPeacefulAndYCheck);
		SpawnPlacements.register(DoomEntities.ARCHVILE.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::passPeacefulAndYCheck);
		SpawnPlacements.register(DoomEntities.LOST_SOUL.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::passPeacefulAndYCheck);
		SpawnPlacements.register(DoomEntities.LOST_SOUL_ETERNAL.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::passPeacefulAndYCheck);
		SpawnPlacements.register(DoomEntities.ZOMBIEMAN.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::passPeacefulAndYCheck);
		SpawnPlacements.register(DoomEntities.SPIDERMASTERMIND.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::passPeacefulAndYCheck);
		SpawnPlacements.register(DoomEntities.ARACHNOTRON.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::passPeacefulAndYCheck);
		SpawnPlacements.register(DoomEntities.MANCUBUS.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::passPeacefulAndYCheck);
		SpawnPlacements.register(DoomEntities.BARON.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::passPeacefulAndYCheck);
		SpawnPlacements.register(DoomEntities.REVENANT.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::passPeacefulAndYCheck);
		SpawnPlacements.register(DoomEntities.IMP.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::passPeacefulAndYCheck);
		SpawnPlacements.register(DoomEntities.PINKY.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::passPeacefulAndYCheck);
		SpawnPlacements.register(DoomEntities.SPECTRE.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::passPeacefulAndYCheck);
		SpawnPlacements.register(DoomEntities.CACODEMON.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::passPeacefulAndYCheck);
		SpawnPlacements.register(DoomEntities.CHAINGUNNER.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::passPeacefulAndYCheck);
		SpawnPlacements.register(DoomEntities.MARAUDER.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::passPeacefulAndYCheck);
		SpawnPlacements.register(DoomEntities.SHOTGUNGUY.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::passPeacefulAndYCheck);
		SpawnPlacements.register(DoomEntities.PAIN.get(), SpawnPlacements.Type.IN_LAVA,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::passPeacefulAndYCheck);
		SpawnPlacements.register(DoomEntities.HELLKNIGHT.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::passPeacefulAndYCheck);
		SpawnPlacements.register(DoomEntities.HELLKNIGHT2016.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::passPeacefulAndYCheck);
		SpawnPlacements.register(DoomEntities.CYBERDEMON.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::passPeacefulAndYCheck);
		SpawnPlacements.register(DoomEntities.UNWILLING.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::passPeacefulAndYCheck);
		SpawnPlacements.register(DoomEntities.POSSESSEDSCIENTIST.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::passPeacefulAndYCheck);
		SpawnPlacements.register(DoomEntities.POSSESSEDSOLDIER.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::passPeacefulAndYCheck);
		SpawnPlacements.register(DoomEntities.ICONOFSIN.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::passPeacefulAndYCheck);
		SpawnPlacements.register(DoomEntities.GORE_NEST.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::passPeacefulAndYCheck);
		SpawnPlacements.register(DoomEntities.MECHAZOMBIE.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::passPeacefulAndYCheck);
		SpawnPlacements.register(DoomEntities.GARGOYLE.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::passPeacefulAndYCheck);
		SpawnPlacements.register(DoomEntities.CUEBALL.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::passPeacefulAndYCheck);
		SpawnPlacements.register(DoomEntities.PROWLER.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::passPeacefulAndYCheck);
		SpawnPlacements.register(DoomEntities.DREADKNIGHT.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::passPeacefulAndYCheck);
		SpawnPlacements.register(DoomEntities.IMP_STONE.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::passPeacefulAndYCheck);
		SpawnPlacements.register(DoomEntities.POSSESSEDWORKER.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::passPeacefulAndYCheck);
		SpawnPlacements.register(DoomEntities.DOOMHUNTER.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::passPeacefulAndYCheck);
		SpawnPlacements.register(DoomEntities.WHIPLASH.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::passPeacefulAndYCheck);
		SpawnPlacements.register(DoomEntities.FIREBARON.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::passPeacefulAndYCheck);
		SpawnPlacements.register(DoomEntities.BARON2016.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::passPeacefulAndYCheck);
		SpawnPlacements.register(DoomEntities.ARMORBARON.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::passPeacefulAndYCheck);
		SpawnPlacements.register(DoomEntities.ARACHNOTRONETERNAL.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::passPeacefulAndYCheck);
		SpawnPlacements.register(DoomEntities.MAYKRDRONE.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::passPeacefulAndYCheck);
		SpawnPlacements.register(DoomEntities.SPIDERMASTERMIND2016.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::passPeacefulAndYCheck);
		SpawnPlacements.register(DoomEntities.BLOODMAYKR.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::passPeacefulAndYCheck);
		SpawnPlacements.register(DoomEntities.ARCHMAKER.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::passPeacefulAndYCheck);
		SpawnPlacements.register(DoomEntities.TENTACLE.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::passPeacefulAndYCheck);
		SpawnPlacements.register(DoomEntities.MOTHERDEMON.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::passPeacefulAndYCheck);
		SpawnPlacements.register(DoomEntities.TURRET.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::passPeacefulAndYCheck);
		SpawnPlacements.register(DoomEntities.SUMMONER.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::passPeacefulAndYCheck);
		SpawnPlacements.register(DoomEntities.REVENANT2016.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DemonEntity::passPeacefulAndYCheck);
	}

	@SubscribeEvent
	public static void entityAttributes(EntityAttributeCreationEvent event) {
		event.put(DoomEntities.GLADIATOR.get(), GladiatorEntity.createAttributes().build());
		event.put(DoomEntities.CYBERDEMON.get(), CyberdemonEntity.createAttributes().build());
		event.put(DoomEntities.ARCHVILE.get(), ArchvileEntity.createAttributes().build());
		event.put(DoomEntities.BARON.get(), BaronEntity.createAttributes().build());
		event.put(DoomEntities.CHAINGUNNER.get(), ChaingunnerEntity.createAttributes().build());
		event.put(DoomEntities.HELLKNIGHT.get(), HellknightEntity.createAttributes().build());
		event.put(DoomEntities.HELLKNIGHT2016.get(), Hellknight2016Entity.createAttributes().build());
		event.put(DoomEntities.ICONOFSIN.get(), IconofsinEntity.createAttributes().build());
		event.put(DoomEntities.IMP.get(), ImpEntity.createAttributes().build());
		event.put(DoomEntities.MANCUBUS.get(), MancubusEntity.createAttributes().build());
		event.put(DoomEntities.MARAUDER.get(), MarauderEntity.createAttributes().build());
		event.put(DoomEntities.PINKY.get(), PinkyEntity.createAttributes().build());
		event.put(DoomEntities.SPECTRE.get(), SpectreEntity.createAttributes().build());
		event.put(DoomEntities.LOST_SOUL.get(), LostSoulEntity.createAttributes().build());
		event.put(DoomEntities.LOST_SOUL_ETERNAL.get(), LostSoulEntity.createAttributes().build());
		event.put(DoomEntities.POSSESSEDSCIENTIST.get(), PossessedScientistEntity.createAttributes().build());
		event.put(DoomEntities.POSSESSEDSOLDIER.get(), PossessedSoldierEntity.createAttributes().build());
		event.put(DoomEntities.REVENANT.get(), RevenantEntity.createAttributes().build());
		event.put(DoomEntities.SHOTGUNGUY.get(), ShotgunguyEntity.createAttributes().build());
		event.put(DoomEntities.ARACHNOTRON.get(), ArachnotronEntity.createAttributes().build());
		event.put(DoomEntities.SPIDERMASTERMIND.get(), SpiderMastermindEntity.createAttributes().build());
		event.put(DoomEntities.UNWILLING.get(), UnwillingEntity.createAttributes().build());
		event.put(DoomEntities.ZOMBIEMAN.get(), ZombiemanEntity.createAttributes().build());
		event.put(DoomEntities.CACODEMON.get(), CacodemonEntity.createAttributes().build());
		event.put(DoomEntities.PAIN.get(), PainEntity.createAttributes().build());
		event.put(DoomEntities.GORE_NEST.get(), GoreNestEntity.createAttributes().build());
		event.put(DoomEntities.MECHAZOMBIE.get(), MechaZombieEntity.createAttributes().build());
		event.put(DoomEntities.GARGOYLE.get(), GargoyleEntity.createAttributes().build());
		event.put(DoomEntities.CUEBALL.get(), CueBallEntity.createAttributes().build());
		event.put(DoomEntities.PROWLER.get(), ProwlerEntity.createAttributes().build());
		event.put(DoomEntities.DREADKNIGHT.get(), Hellknight2016Entity.createAttributes().build());
		event.put(DoomEntities.IMP_STONE.get(), ImpStoneEntity.createAttributes().build());
		event.put(DoomEntities.POSSESSEDWORKER.get(), PossessedScientistEntity.createAttributes().build());
		event.put(DoomEntities.DOOMHUNTER.get(), DoomHunterEntity.createAttributes().build());
		event.put(DoomEntities.WHIPLASH.get(), WhiplashEntity.createAttributes().build());
		event.put(DoomEntities.BARON2016.get(), BaronEntity.createAttributes().build());
		event.put(DoomEntities.ARMORBARON.get(), ArmoredBaronEntity.createAttributes().build());
		event.put(DoomEntities.ARACHNOTRONETERNAL.get(), ArachnotronEntity.createAttributes().build());
		event.put(DoomEntities.MAYKRDRONE.get(), MaykrDroneEntity.createAttributes().build());
		event.put(DoomEntities.SPIDERMASTERMIND2016.get(), SpiderMastermind2016Entity.createAttributes().build());
		event.put(DoomEntities.BLOODMAYKR.get(), BloodMaykrEntity.createAttributes().build());
		event.put(DoomEntities.ARCHMAKER.get(), ArchMakyrEntity.createAttributes().build());
		event.put(DoomEntities.FIREBARON.get(), FireBaronEntity.createAttributes().build());
		event.put(DoomEntities.TENTACLE.get(), TentacleEntity.createAttributes().build());
		event.put(DoomEntities.MOTHERDEMON.get(), MotherDemonEntity.createAttributes().build());
		event.put(DoomEntities.TURRET.get(), TurretEntity.createAttributes().build());
		event.put(DoomEntities.SUMMONER.get(), SummonerEntity.createAttributes().build());
		event.put(DoomEntities.REVENANT2016.get(), Revenant2016Entity.createAttributes().build());
	}
}