package mod.azure.doom.util;

import mod.azure.doom.DoomMod;
import mod.azure.doom.entity.tierambient.CueBallEntity;
import mod.azure.doom.entity.tierambient.GoreNestEntity;
import mod.azure.doom.entity.tierambient.TentacleEntity;
import mod.azure.doom.entity.tierambient.TurretEntity;
import mod.azure.doom.entity.tierboss.ArchMakyrEntity;
import mod.azure.doom.entity.tierboss.IconofsinEntity;
import mod.azure.doom.entity.tierboss.MotherDemonEntity;
import mod.azure.doom.entity.tierboss.SpiderMastermind2016Entity;
import mod.azure.doom.entity.tierboss.SpiderMastermindEntity;
import mod.azure.doom.entity.tierfodder.ChaingunnerEntity;
import mod.azure.doom.entity.tierfodder.GargoyleEntity;
import mod.azure.doom.entity.tierfodder.Imp2016Entity;
import mod.azure.doom.entity.tierfodder.ImpEntity;
import mod.azure.doom.entity.tierfodder.ImpStoneEntity;
import mod.azure.doom.entity.tierfodder.LostSoulEntity;
import mod.azure.doom.entity.tierfodder.MaykrDroneEntity;
import mod.azure.doom.entity.tierfodder.MechaZombieEntity;
import mod.azure.doom.entity.tierfodder.NightmareImpEntity;
import mod.azure.doom.entity.tierfodder.PossessedScientistEntity;
import mod.azure.doom.entity.tierfodder.PossessedSoldierEntity;
import mod.azure.doom.entity.tierfodder.ShotgunguyEntity;
import mod.azure.doom.entity.tierfodder.UnwillingEntity;
import mod.azure.doom.entity.tierfodder.ZombiemanEntity;
import mod.azure.doom.entity.tierheavy.ArachnotronEntity;
import mod.azure.doom.entity.tierheavy.BloodMaykrEntity;
import mod.azure.doom.entity.tierheavy.CacodemonEntity;
import mod.azure.doom.entity.tierheavy.Hellknight2016Entity;
import mod.azure.doom.entity.tierheavy.HellknightEntity;
import mod.azure.doom.entity.tierheavy.MancubusEntity;
import mod.azure.doom.entity.tierheavy.PainEntity;
import mod.azure.doom.entity.tierheavy.Pinky2016;
import mod.azure.doom.entity.tierheavy.PinkyEntity;
import mod.azure.doom.entity.tierheavy.ProwlerEntity;
import mod.azure.doom.entity.tierheavy.Revenant2016Entity;
import mod.azure.doom.entity.tierheavy.RevenantEntity;
import mod.azure.doom.entity.tierheavy.SpectreEntity;
import mod.azure.doom.entity.tierheavy.WhiplashEntity;
import mod.azure.doom.entity.tiersuperheavy.ArchvileEntity;
import mod.azure.doom.entity.tiersuperheavy.ArmoredBaronEntity;
import mod.azure.doom.entity.tiersuperheavy.BaronEntity;
import mod.azure.doom.entity.tiersuperheavy.Cyberdemon2016Entity;
import mod.azure.doom.entity.tiersuperheavy.CyberdemonEntity;
import mod.azure.doom.entity.tiersuperheavy.DoomHunterEntity;
import mod.azure.doom.entity.tiersuperheavy.FireBaronEntity;
import mod.azure.doom.entity.tiersuperheavy.MarauderEntity;
import mod.azure.doom.entity.tiersuperheavy.SummonerEntity;
import mod.azure.doom.util.registry.ModEntityTypes;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.SpawnPlacements;
import net.minecraft.world.level.levelgen.Heightmap;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.event.entity.EntityAttributeCreationEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod.EventBusSubscriber;

@EventBusSubscriber(modid = DoomMod.MODID, bus = EventBusSubscriber.Bus.MOD)
public class ModEventSubscriber {

	@SubscribeEvent
	public static void registerEntities(final RegistryEvent.Register<EntityType<?>> event) {
		SpawnPlacements.register(ModEntityTypes.ARCHVILE.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, ArchvileEntity::spawning);
		SpawnPlacements.register(ModEntityTypes.LOST_SOUL.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, LostSoulEntity::spawning);
		SpawnPlacements.register(ModEntityTypes.ZOMBIEMAN.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, ZombiemanEntity::spawning);
		SpawnPlacements.register(ModEntityTypes.SPIDERMASTERMIND.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, SpiderMastermindEntity::spawning);
		SpawnPlacements.register(ModEntityTypes.ARACHNOTRON.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, ArachnotronEntity::spawning);
		SpawnPlacements.register(ModEntityTypes.MANCUBUS.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, MancubusEntity::spawning);
		SpawnPlacements.register(ModEntityTypes.BARON.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, BaronEntity::spawning);
		SpawnPlacements.register(ModEntityTypes.REVENANT.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, RevenantEntity::spawning);
		SpawnPlacements.register(ModEntityTypes.IMP.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, ImpEntity::spawning);
		SpawnPlacements.register(ModEntityTypes.NIGHTMARE_IMP.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, NightmareImpEntity::spawning);
		SpawnPlacements.register(ModEntityTypes.PINKY.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, PinkyEntity::spawning);
		SpawnPlacements.register(ModEntityTypes.SPECTRE.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, SpectreEntity::spawning);
		SpawnPlacements.register(ModEntityTypes.CACODEMON.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, CacodemonEntity::spawning);
		SpawnPlacements.register(ModEntityTypes.IMP2016.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Imp2016Entity::spawning);
		SpawnPlacements.register(ModEntityTypes.CHAINGUNNER.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, ChaingunnerEntity::spawning);
		SpawnPlacements.register(ModEntityTypes.MARAUDER.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, MarauderEntity::spawning);
		SpawnPlacements.register(ModEntityTypes.SHOTGUNGUY.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, ShotgunguyEntity::spawning);
		SpawnPlacements.register(ModEntityTypes.PAIN.get(), SpawnPlacements.Type.IN_LAVA,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, PainEntity::spawning);
		SpawnPlacements.register(ModEntityTypes.HELLKNIGHT.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, HellknightEntity::spawning);
		SpawnPlacements.register(ModEntityTypes.HELLKNIGHT2016.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Hellknight2016Entity::spawning);
		SpawnPlacements.register(ModEntityTypes.CYBERDEMON.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, CyberdemonEntity::checkGhastSpawnRules);
		SpawnPlacements.register(ModEntityTypes.CYBERDEMON2016.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Cyberdemon2016Entity::spawning);
		SpawnPlacements.register(ModEntityTypes.UNWILLING.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, UnwillingEntity::spawning);
		SpawnPlacements.register(ModEntityTypes.POSSESSEDSCIENTIST.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, PossessedScientistEntity::spawning);
		SpawnPlacements.register(ModEntityTypes.POSSESSEDSOLDIER.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, PossessedSoldierEntity::spawning);
		SpawnPlacements.register(ModEntityTypes.ICONOFSIN.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, IconofsinEntity::spawning);
		SpawnPlacements.register(ModEntityTypes.GORE_NEST.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, GoreNestEntity::spawning);
		SpawnPlacements.register(ModEntityTypes.MECHAZOMBIE.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, MechaZombieEntity::spawning);
		SpawnPlacements.register(ModEntityTypes.GARGOYLE.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, GargoyleEntity::spawning);
		SpawnPlacements.register(ModEntityTypes.CUEBALL.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, CueBallEntity::spawning);
		SpawnPlacements.register(ModEntityTypes.PROWLER.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, ProwlerEntity::spawning);
		SpawnPlacements.register(ModEntityTypes.DREADKNIGHT.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Hellknight2016Entity::spawning);
		SpawnPlacements.register(ModEntityTypes.IMP_STONE.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, ImpStoneEntity::spawning);
		SpawnPlacements.register(ModEntityTypes.TYRANT.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Cyberdemon2016Entity::spawning);
		SpawnPlacements.register(ModEntityTypes.POSSESSEDWORKER.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, PossessedScientistEntity::spawning);
		SpawnPlacements.register(ModEntityTypes.DOOMHUNTER.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, DoomHunterEntity::spawning);
		SpawnPlacements.register(ModEntityTypes.WHIPLASH.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, WhiplashEntity::spawning);
		SpawnPlacements.register(ModEntityTypes.PINKY2016.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Pinky2016::spawning);
		SpawnPlacements.register(ModEntityTypes.FIREBARON.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, FireBaronEntity::spawning);
		SpawnPlacements.register(ModEntityTypes.BARON2016.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, BaronEntity::spawning);
		SpawnPlacements.register(ModEntityTypes.ARMORBARON.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, ArmoredBaronEntity::spawning);
		SpawnPlacements.register(ModEntityTypes.ARACHNOTRONETERNAL.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, ArachnotronEntity::spawning);
		SpawnPlacements.register(ModEntityTypes.MAYKRDRONE.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, MaykrDroneEntity::spawning);
		SpawnPlacements.register(ModEntityTypes.SPIDERMASTERMIND2016.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, SpiderMastermind2016Entity::spawn);
		SpawnPlacements.register(ModEntityTypes.BLOODMAYKR.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, BloodMaykrEntity::spawning);
		SpawnPlacements.register(ModEntityTypes.ARCHMAKER.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, ArchMakyrEntity::spawning);
		SpawnPlacements.register(ModEntityTypes.ARCHVILEETERNAL.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, ArchvileEntity::spawning);
		SpawnPlacements.register(ModEntityTypes.TENTACLE.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, TentacleEntity::spawning);
		SpawnPlacements.register(ModEntityTypes.MOTHERDEMON.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, MotherDemonEntity::spawning);
		SpawnPlacements.register(ModEntityTypes.TURRET.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, TurretEntity::spawning);
		SpawnPlacements.register(ModEntityTypes.SUMMONER.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, SummonerEntity::spawning);
		SpawnPlacements.register(ModEntityTypes.REVENANT2016.get(), SpawnPlacements.Type.ON_GROUND,
				Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Revenant2016Entity::spawning);
	}

	@SubscribeEvent
	public static void entityAttributes(EntityAttributeCreationEvent event) {
		event.put(ModEntityTypes.CYBERDEMON.get(), CyberdemonEntity.createAttributes().build());
		event.put(ModEntityTypes.ARCHVILE.get(), ArchvileEntity.createAttributes().build());
		event.put(ModEntityTypes.BARON.get(), BaronEntity.createAttributes().build());
		event.put(ModEntityTypes.CHAINGUNNER.get(), ChaingunnerEntity.createAttributes().build());
		event.put(ModEntityTypes.CYBERDEMON2016.get(), Cyberdemon2016Entity.createAttributes().build());
		event.put(ModEntityTypes.HELLKNIGHT.get(), HellknightEntity.createAttributes().build());
		event.put(ModEntityTypes.HELLKNIGHT2016.get(), Hellknight2016Entity.createAttributes().build());
		event.put(ModEntityTypes.ICONOFSIN.get(), IconofsinEntity.createAttributes().build());
		event.put(ModEntityTypes.IMP2016.get(), Imp2016Entity.createAttributes().build());
		event.put(ModEntityTypes.NIGHTMARE_IMP.get(), NightmareImpEntity.createAttributes().build());
		event.put(ModEntityTypes.IMP.get(), ImpEntity.createAttributes().build());
		event.put(ModEntityTypes.MANCUBUS.get(), MancubusEntity.createAttributes().build());
		event.put(ModEntityTypes.MARAUDER.get(), MarauderEntity.createAttributes().build());
		event.put(ModEntityTypes.PINKY.get(), PinkyEntity.createAttributes().build());
		event.put(ModEntityTypes.SPECTRE.get(), SpectreEntity.createAttributes().build());
		event.put(ModEntityTypes.LOST_SOUL.get(), LostSoulEntity.createAttributes().build());
		event.put(ModEntityTypes.POSSESSEDSCIENTIST.get(), PossessedScientistEntity.createAttributes().build());
		event.put(ModEntityTypes.POSSESSEDSOLDIER.get(), PossessedSoldierEntity.createAttributes().build());
		event.put(ModEntityTypes.REVENANT.get(), RevenantEntity.createAttributes().build());
		event.put(ModEntityTypes.SHOTGUNGUY.get(), ShotgunguyEntity.createAttributes().build());
		event.put(ModEntityTypes.ARACHNOTRON.get(), ArachnotronEntity.createAttributes().build());
		event.put(ModEntityTypes.SPIDERMASTERMIND.get(), SpiderMastermindEntity.createAttributes().build());
		event.put(ModEntityTypes.UNWILLING.get(), UnwillingEntity.createAttributes().build());
		event.put(ModEntityTypes.ZOMBIEMAN.get(), ZombiemanEntity.createAttributes().build());
		event.put(ModEntityTypes.CACODEMON.get(), CacodemonEntity.createAttributes().build());
		event.put(ModEntityTypes.PAIN.get(), PainEntity.createAttributes().build());
		event.put(ModEntityTypes.GORE_NEST.get(), GoreNestEntity.createAttributes().build());
		event.put(ModEntityTypes.MECHAZOMBIE.get(), MechaZombieEntity.createAttributes().build());
		event.put(ModEntityTypes.GARGOYLE.get(), GargoyleEntity.createAttributes().build());
		event.put(ModEntityTypes.CUEBALL.get(), CueBallEntity.createAttributes().build());
		event.put(ModEntityTypes.PROWLER.get(), ProwlerEntity.createAttributes().build());
		event.put(ModEntityTypes.DREADKNIGHT.get(), Hellknight2016Entity.createAttributes().build());
		event.put(ModEntityTypes.IMP_STONE.get(), ImpStoneEntity.createAttributes().build());
		event.put(ModEntityTypes.TYRANT.get(), Cyberdemon2016Entity.createAttributes().build());
		event.put(ModEntityTypes.POSSESSEDWORKER.get(), PossessedScientistEntity.createAttributes().build());
		event.put(ModEntityTypes.DOOMHUNTER.get(), DoomHunterEntity.createAttributes().build());
		event.put(ModEntityTypes.WHIPLASH.get(), WhiplashEntity.createAttributes().build());
		event.put(ModEntityTypes.PINKY2016.get(), Pinky2016.createAttributes().build());
		event.put(ModEntityTypes.BARON2016.get(), BaronEntity.createAttributes().build());
		event.put(ModEntityTypes.ARMORBARON.get(), ArmoredBaronEntity.createAttributes().build());
		event.put(ModEntityTypes.ARACHNOTRONETERNAL.get(), ArachnotronEntity.createAttributes().build());
		event.put(ModEntityTypes.MAYKRDRONE.get(), MaykrDroneEntity.createAttributes().build());
		event.put(ModEntityTypes.SPIDERMASTERMIND2016.get(), SpiderMastermind2016Entity.createAttributes().build());
		event.put(ModEntityTypes.BLOODMAYKR.get(), BloodMaykrEntity.createAttributes().build());
		event.put(ModEntityTypes.ARCHMAKER.get(), ArchMakyrEntity.createAttributes().build());
		event.put(ModEntityTypes.FIREBARON.get(), FireBaronEntity.createAttributes().build());
		event.put(ModEntityTypes.ARCHVILEETERNAL.get(), ArchvileEntity.createAttributes().build());
		event.put(ModEntityTypes.TENTACLE.get(), TentacleEntity.createAttributes().build());
		event.put(ModEntityTypes.MOTHERDEMON.get(), MotherDemonEntity.createAttributes().build());
		event.put(ModEntityTypes.TURRET.get(), TurretEntity.createAttributes().build());
		event.put(ModEntityTypes.SUMMONER.get(), SummonerEntity.createAttributes().build());
		event.put(ModEntityTypes.REVENANT2016.get(), Revenant2016Entity.createAttributes().build());
	}
}