package mod.azure.doom.items.enums;

public enum GunTypeEnum {
    BALLISTA, BFG, BFG9000, CHAINGUN, DGAUSS, DPLASMA, DSHOTGUN, HEAVYCANNON, PISTOL, PLAMSA, ROCKETLAUNCHER, SHOTGUN,
    SUPERSHOTGUN, UNMAKER, UNMAYKR
}
